# Action 名稱
name: Deploy

# 觸發時機，當推送到分支 main 時
on:
  push:
    branches: [ main ]

# 執行的工作
jobs:
  # 工作名稱
  deploy:
    # 執行工作的虛擬機作業系統
    runs-on: ubuntu-latest
    
    # 工作步驟
    steps:
      # 步驟一：複製程式碼 (這裡改成 v4)
      - name: checkout
        uses: actions/checkout@v4
      
      # 步驟二：安裝套件並編譯
      - name: Install and Build
        run: |
          npm install
          npm run build
      
      # 步驟三：部署到 gh-pages 分支
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist